### ISSUE TITLE
Please consider xwrited

### ISSUE THREAD

**Issue by thkoch2001** [rfjakob/systembus-notify#13]
https://code.guido-berhoerster.org/projects/xwrited/

I packaged this for Debian some years ago:
https://tracker.debian.org/pkg/xwrited

Software description:

> The xwrited utility displays write(1) and wall(1) messages as desktop notifications. A notification daemon compliant to the freedesktop.org Desktop Notification Specification draft needs to be running in order to display the notifications.

**Comment by rfjakob** [comment]
Didn't know about this one, thanks. But seems orthogonal to systembus-notify.
